### ISSUE TITLE
Q/A: How to install programs without keeping their their extension. (e. g: `dbin add mpv.appimage` installed as `mpv`)

### ISSUE THREAD

**Issue by candrapersada** [xplshn/dbin#28]

**Comment by xplshn** [comment]
You can update `dbin` to version 1.6 (download it from here: https://github.com/xplshn/dbin/releases/tag/1.6), then use the following config file in order for `dbin` to behave that way:

Put this at `~/.config/dbin/dbin.yaml`
```yaml
Repositories:
- URL: https://d.xplshn.com.ar/misc/cmd/1.6/amd64_linux.lite.cbor.zst
  pubKeys:
    bincache: https://meta.pkgforge.dev/bincache/minisign.pub
    pkgcache: https://meta.pkgforge.dev/pkgcache/minisign.pub
  syncInterval: 6h0m0s
CreateLicenses: true
SearchResultsLimit: 9999
PbarStyle: 1
Truncation: false
RetakeOwnership: false
IntegrationHooks: true
Hooks:
  commands:
    "*":
      integrationCommand: sh -c "if [ \"$DBIN_HOOK_BINARY_EXT\" = \".AppBundle\" ]; then NF=\"$(basename \"$DBIN_HOOK_BINARY\" | cut -d'.' -f1)\"; mv \"$DBIN_HOOK_BINARY\" \"$DBIN_INSTALL_DIR/$NF\"; elif [ -n \"$DBIN_HOOK_BINARY_EXT\" ]; then mv \"$DBIN_HOOK_BINARY\" \"${DBIN_HOOK_BINARY%.*}\"; fi; $DBIN info > \"${DBIN_CACHE_DIR}/.info\""
      deintegrationCommand: sh -c "if [ \"$DBIN_HOOK_BINARY_EXT\" = \".AppBundle\" ]; then NF=\"$(basename \"$DBIN_HOOK_BINARY\" | cut -d'.' -f1)\"; rm -f \"$DBIN_INSTALL_DIR/$NF\"; elif [ -n \"$DBIN_HOOK_BINARY_EXT\" ]; then rm -f \"${DBIN_INSTALL_DIR}/$(basename \"${DBIN_HOOK_BINARY%.*}\")\"; fi; $DBIN info > \"${DBIN_CACHE_DIR}/.info\""
      runFromCache: true
      silent: true
      nop: false

```

EDIT: @candrapersada I updated the hook to handle an edge-case. For v1.7, I'll make the hooks have an interpreter type and be multi-line. As shell looks terribly this way and its not readable enough
